_BASE_: transformer.yml
reduce_on_plateau: true
noamopt: false
learning_rate: 0.00001
learning_rate_decay_start: -1

self_critical_after: 0
max_epochs: 60
train_beam_size: 3
checkpoint_path: "log_GeoRSCLIP_mul2_AwareTrans5Dec+4_sc"

cached_tokens: nwpu-25-idxs